---
- name: Create base directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
    owner: root
    group: root
  loop:
    - { path: "{{ guacamole_docker_container_path }}", mode: '0710' }
    - { path: "{{ guacamole_docker_data_path }}", mode: '0755' }
    - { path: "{{ guacamole_docker_secrets_path }}", mode: '0710' }

- name: Create directories for mounting to Docker containers
  ansible.builtin.file:
    path: "{{ guacamole_docker_data_path }}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode | default('0755') }}"
    owner: "{{ item.uid | default('root') }}"
    group: "{{ item.gid | default('root') }}"
  loop:
    - { path: 'guacd-drive', mode: '0700', uid: '1000', gid: '1000' }
    - { path: 'guacd-record', mode: '0750', uid: '1000', gid: '1000' }
    - { path: 'postgres-data' }

- name: Copy Docker Compose file
  ansible.builtin.copy:
    dest: "{{ guacamole_docker_container_path }}/docker-compose.yml"
    src: docker-compose.yml
    mode: "0644"
    owner: root
    group: root

- name: Copy initdb file for postgres
  ansible.builtin.copy:
    dest: "{{ guacamole_docker_data_path }}/initdb.sql"
    src: initdb.sql
    mode: "0644"
    owner: root
    group: root

- name: Generate password for postgres
  ansible.builtin.copy:
    dest: "{{ guacamole_docker_secrets_path }}/guacamole-docker-db-passwd"
    content: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
    mode: "0600"
    owner: root
    group: root
    force: false

- name: Fetch password for postgres
  ansible.builtin.slurp:
    src: "{{ guacamole_docker_secrets_path }}/guacamole-docker-db-passwd"
  register: guacamole_docker_password_slurp

- name: Download branding extension for Guacamole
  ansible.builtin.get_url:
    dest: "{{ guacamole_docker_data_path }}/branding-adfc-hh.jar"
    url: "https://github.com/ADFC-Hamburg/guacamole-branding/releases/download/{{ guacamole_docker_branding_version }}/branding-adfc-hh.jar"
    checksum: "{{ guacamole_docker_branding_checksum }}"
    mode: "0644"
    owner: root
    group: root
    force: true
  register: guacamole_docker_branding_result

- name: Create variables file for Docker Compose
  ansible.builtin.template:
    dest: "{{ guacamole_docker_container_path }}/.env"
    src: env.j2
    mode: "0600"
    owner: root
    group: root

- name: Stop and remove service
  ansible.builtin.command: 
    cmd: docker-compose down
    chdir: "{{ guacamole_docker_container_path }}"
  when: guacamole_docker_branding_result.changed
  register: guacamole_docker_down_result
  changed_when: "'... done' in guacamole_docker_down_result.stderr"

- name: Create and start service
  ansible.builtin.command: 
    cmd: docker-compose up --detach
    chdir: "{{ guacamole_docker_container_path }}"
  register: guacamole_docker_up_result
  changed_when: "'... done' in guacamole_docker_up_result.stderr"

- name: Create Apache File
  ansible.builtin.template:
    dest: "/etc/apache2/ucs-sites.conf.d/guacamole_ansible.conf"
    src: "apache.conf.j2"
    mode: "0644"
    owner: root
    group: root
  notify: Reload apache
