#!/bin/bash
# siehe /usr/share/doc/vpnc/README.gz
# verhindert das setzen eines neuen DNS Resolvers
# this effectively disables changes to /etc/resolv.conf
INTERNAL_IP4_DNS=

# This sets up split networking regardless
# of the concentrators specifications.
# You can add as many routes as you want,
# but you must set the counter $CISCO_SPLIT_INC
# accordingly
CISCO_SPLIT_INC=1
CISCO_SPLIT_INC_0_ADDR=192.168.123.0
CISCO_SPLIT_INC_0_MASK=255.255.255.0
CISCO_SPLIT_INC_0_MASKLEN=24
CISCO_SPLIT_INC_0_PROTOCOL=0
CISCO_SPLIT_INC_0_SPORT=0
CISCO_SPLIT_INC_0_DPORT=0
. /usr/share/vpnc-scripts/vpnc-script
if [ "$reason" == "connect" ]; then
   /usr/local/sbin/adfc-knock
fi
